fix PublishEvent: Add ClientInfo
centrifugal/centrifuge-java pull request #29
Opened 2021-08-28 07:05 UTC by clmno

In `centrifuge-go` a publish event (Publication struct) has 3 values - `Offset`, `Data` and `Info` ([view implementation](https://github.com/centrifugal/centrifuge-go/blob/595eded263578dd44cb6f2b6a8d3a08ac34b8f4a/protocol.go#L18)). But the java client only has 2 - offset and data.
This commit adds `info` to the `PublishEvent` class and sets it in the Client class.

2021-08-28 08:50 UTC, FZambia requested changes
Thanks! Added some review comments

2021-08-28 08:50 UTC, FZambia commented on centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java
> +                    event.setInfo(info);
Should not be set if it's not set in incoming Publication - i.e. should be null, not an empty ClientInfo object as done here.

2021-08-28 08:50 UTC, FZambia commented on centrifuge/src/main/java/io/github/centrifugal/centrifuge/PublishEvent.java
> +    public ClientInfo getInfo() {
Could you please also add this to `ServerPublishEvent` and set it accordingly?

2021-08-30 10:46 UTC, clmno commented
@FZambia I've made the changes you've requested.
1. ClientInfo set to `null` if the protocol.ClientInfo == null
2. Added ClientInfo for `PublishEvent`
2. Added the same for `ServerPublishEvent`

Please review and let me know

2021-08-30 10:48 UTC, clmno reviewed
I've made the necessary changes

2021-08-30 19:01 UTC, merged

2021-08-30 19:01 UTC, FZambia commented
@clmno great, thanks!